### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DankoIT/proxoid#51]
```
What steps will reproduce the problem?
1. Start proxoid
2. back (close the activity)
3. wait

What is the expected output? What do you see instead?

No crash expected ; and working proxy.
After some time, a crash dialog is shown and the proxy is not available on the 
pc.

What version of the product are you using? On what operating system?

The latest version on the market.
On Android MiniCM 7 (it's android 2.2.1)

Please provide any additional information below.

Here is the stack trace from logcat :

I/ActivityManager( 1437): Start proc eu.codlab.proxurdroid for service 
eu.codlab.proxurdroid/.ProxyService: pid=15475 uid=10077 gids={3003}
W/Service (15475): setForeground: ignoring old API call on 
eu.codlab.proxurdroid.ProxyService
D/update  (15475):  2130837504
W/dalvikvm(15475): threadid=10: thread exiting with uncaught exception 
(group=0x40018560)
I/ActivityManager( 1437): Start proc com.cyanogenmod.cmparts for broadcast 
com.cyanogenmod.cmparts/.intents.LEDNotificationReceiver: pid=15487 uid=1000 
gids={3002, 3001, 3003, 1015}
E/AndroidRuntime(15475): FATAL EXCEPTION: Timer-0
E/AndroidRuntime(15475): java.lang.NullPointerException
E/AndroidRuntime(15475):        at 
eu.codlab.proxurdroid.ProxyService.update(ProxyService.java:197)
E/AndroidRuntime(15475):        at 
eu.codlab.proxurdroid.ProxyService.updateNotificationDown(ProxyService.java:244)
E/AndroidRuntime(15475):        at 
eu.codlab.proxurdroid.service.TimerNotif.run(TimerNotif.java:26)
E/AndroidRuntime(15475):        at java.util.Timer$TimerImpl.run(Timer.java:284)
D/dalvikvm(15475): GC_EXTERNAL_ALLOC freed 61K, 50% free 2718K/5379K, external 
0K/0K, paused 260ms
D/ProxoidService(15475): OnCreate
D/dalvikvm(15416): GC_CONCURRENT freed 565K, 48% free 3368K/6471K, external 
1183K/1364K, paused 104ms+7ms
D/szipinf (15487): Initializing inflate state
W/Resources(15440): Converting to string: TypedValue{t=0x10/d=0xffffffff a=-1}
```

Original issue reported on code.google.com by `cbo...@gmail.com` on 20 Jul 2012 at 8:30

**Comment by GoogleCodeExporter** [comment]
```
In fact it also happens when starting the app (and it happens a lot).

You have to start the app again and again until the activity starts.

Here is another stack trace :

W/Service (16359): setForeground: ignoring old API call on 
eu.codlab.proxurdroid.ProxyService
D/update  (16359):  2130837504
W/dalvikvm(16359): threadid=18: thread exiting with uncaught exception 
(group=0x40018560)
E/AndroidRuntime(16359): FATAL EXCEPTION: Timer-3
E/AndroidRuntime(16359): java.lang.NullPointerException
E/AndroidRuntime(16359):        at 
eu.codlab.proxurdroid.ProxyService.update(ProxyService.java:197)
E/AndroidRuntime(16359):        at 
eu.codlab.proxurdroid.ProxyService.updateNotificationDown(ProxyService.java:244)
E/AndroidRuntime(16359):        at 
eu.codlab.proxurdroid.service.TimerNotif.run(TimerNotif.java:26)
E/AndroidRuntime(16359):        at java.util.Timer$TimerImpl.run(Timer.java:284)
I/ActivityManager( 1437): Start proc com.cyanogenmod.cmparts for broadcast 
com.cyanogenmod.cmparts/.intents.LEDNotificationReceiver: p
id=16378 uid=1000 gids={3002, 3001, 3003, 1015}
W/ActivityManager( 1437):   Force finishing activity 
eu.codlab.proxurdroid/.ProxUrDroid
D/ProxoidService(16359): OnCreate
```

Original comment by `cbo...@gmail.com` on 20 Jul 2012 at 8:57
