### ISSUE TITLE
Proxy stops responding

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DankoIT/proxoid#7]
```
What steps will reproduce the problem?
1. Launch app 
2. surf web with PC
3. after some time their is no internet. 
4. crash proxoid on G1 and restart and internet works again.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `peeps...@gmail.com` on 29 Jun 2009 at 11:19

**Comment by GoogleCodeExporter** [comment]
```
I think I know why ...
I'll see
```

Original comment by `mike.bar...@gmail.com` on 2 Jul 2009 at 7:31
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
so? did you found the problem?

on my phone (rogers htc) I just have to stop/start proxoid and it works again.

Thank's!
```

Original comment by `duesentr...@gmail.com` on 2 Sep 2009 at 7:17

**Comment by GoogleCodeExporter** [comment]
```
same problem for me
```

Original comment by `christophedeze` on 28 Dec 2009 at 9:30

**Comment by GoogleCodeExporter** [comment]
```
Looking into it.
```

Original comment by `RedBMas...@gmail.com` on 9 Feb 2010 at 9:01
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
This maybe liked to a flag issue that was recently fixed, look for a new 
release this
weekend or early next week.
```

Original comment by `RedBMas...@gmail.com` on 10 Feb 2010 at 10:33

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
same issue here. any word on a new release?
```

Original comment by `ryph...@gmail.com` on 27 Feb 2010 at 1:23

**Comment by GoogleCodeExporter** [comment]
```
Any word on an update to fix this issue?
```

Original comment by `markwa...@gmail.com` on 26 Mar 2010 at 10:27

**Comment by GoogleCodeExporter** [comment]
```
Also, until there is a fix is there an adb command to run to restart proxoid on 
the
droid?  The droid's connected in another room to a server, and the constant 
resetting
would be less noticeable if I wrote a script to detect and restart the process.
```

Original comment by `linuxsne...@gmail.com` on 27 Mar 2010 at 10:00

**Comment by GoogleCodeExporter** [comment]
```
Experiencing the same issue on Sprint Hero. Proxoid frequently stops working. 
Service 
resumes once I restart the program on phone.
```

Original comment by `josel...@gmail.com` on 24 Apr 2010 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
I took abit of time to investigate the problem, and blogged about it here: 
http://www.supermind.org/blog/660/solved-connection-reset-problems-with-proxoid

The issue is with Proxoid's use of NIO selectors, and Apache Harmony's bug with 
not 
closing selectors: http://code.google.com/p/android/issues/detail?id=4825

As far as I can tell, there's no easy fix to the problem. The approach I took 
was to 
rewrite the proxy server implementation.

However, my code is untested and I'm not really available to offer support for 
it.
```

Original comment by `superkelvint@gmail.com` on 2 May 2010 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
still no updates on this?
It seems to be getting worse. 
```

Original comment by `tehgri...@googlemail.com` on 16 Jun 2010 at 7:58

**Comment by GoogleCodeExporter** [comment]
```
See 
http://www.supermind.org/blog/660/solved-connection-reset-problems-with-proxoid 
for a fix which solves the connection reset issue, and also supports SSH. 

Download link included. Source available on request (GPL and BSD, with some 
proprietary code).
```

Original comment by `superkelvint@gmail.com` on 17 Jun 2010 at 9:05

**Comment by GoogleCodeExporter** [comment]
```
@superkelvint:
That one doesn't work for me. CM7.2 (Android 2.3.7)

Log:
W/System.err(11872): java.io.IOException: Empty request
W/System.err(11872):    at org.supermind.Request.read(Request.java:58)
W/System.err(11872):    at org.supermind.Client.read(Client.java:53)
W/System.err(11872):    at 
org.supermind.SupermindProxyServer$RequestHandler.run(SupermindProxyServer.java:
108)
W/System.err(11872):    at 
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
W/System.err(11872):    at 
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
W/System.err(11872):    at 
java.util.concurrent.FutureTask.run(FutureTask.java:138)
W/System.err(11872):    at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
W/System.err(11872):    at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
W/System.err(11872):    at java.lang.Thread.run(Thread.java:1019)
W/System.err(11872): java.net.SocketTimeoutException
W/System.err(11872):    at 
org.apache.harmony.luni.net.PlainSocketImpl.read(PlainSocketImpl.java:461)
W/System.err(11872):    at 
org.apache.harmony.luni.net.SocketInputStream.read(SocketInputStream.java:85)
W/System.err(11872):    at 
org.apache.harmony.luni.net.SocketInputStream.read(SocketInputStream.java:65)
W/System.err(11872):    at 
java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:140)
W/System.err(11872):    at 
java.io.BufferedInputStream.read(BufferedInputStream.java:225)
W/System.err(11872):    at org.supermind.Message.readLine(Message.java:50)
W/System.err(11872):    at org.supermind.Request.read(Request.java:56)
W/System.err(11872):    at org.supermind.Client.read(Client.java:53)
W/System.err(11872):    at 
org.supermind.SupermindProxyServer$RequestHandler.run(SupermindProxyServer.java:
108)
W/System.err(11872):    at 
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
W/System.err(11872):    at 
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
W/System.err(11872):    at 
java.util.concurrent.FutureTask.run(FutureTask.java:138)
W/System.err(11872):    at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
W/System.err(11872):    at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
W/System.err(11872):    at java.lang.Thread.run(Thread.java:1019)

```

Original comment by `nathan.r...@gmail.com` on 30 Jun 2012 at 10:35
